version: 0.2
phases:
  install:
    commands:
      - echo "Instalando dependencias..."
      - npm install -g newman
  pre_build:
    commands:
      - echo Loguearse dentro de Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 781000631387.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Inicio compilación en `date`
      - echo Construyendo imagen de docker...
      - docker build -t localhost_app_respository:latest .
      - echo Etiquetando imagen de docker...
      - docker tag localhost_app_respository:latest 781000631387.dkr.ecr.us-east-2.amazonaws.com/localhost_app_respository:latest
  post_build:
    commands:
      - echo Creación de imagen completada en `date`
      - echo Enviar  imagen al repositorio de AWS...
      - docker push 781000631387.dkr.ecr.us-east-2.amazonaws.com/localhost_app_respository:latest
      - echo Escribiendo el archivo de definición de la imagen...
      - printf '[{"name":"Container-app-python","imageUri":"781000631387.dkr.ecr.us-east-2.amazonaws.com/localhost_app_respository:latest"}]' > imageDefinitions.json
      - printf '{"ImageURI":"781000631387.dkr.ecr.us-east-2.amazonaws.com/localhost_app_respository:latest"}' > imageDetail.json
      - cat imageDefinitions.json
  acceptance_test:
    commands:
      - echo "Ejecutando pruebas de aceptación..."
      - newman run acceptance-test/blacklist-collection.postman_collection.json -e acceptance-test/fargate.postman_environment.json
      - echo "Pruebas de aceptación completadas..."
artifacts:
  files:
    - taskdef.json
    - imageDefinitions.json
    - imageDetail.json
    - appspec.json
  name: BuildArtifact
